# render.yaml
services:
  - type: web
    name: artgallery
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn artgallery.wsgi --log-file -"
    envVars:
      - key: DJANGO_SECRET_KEY
        value: 1f8d44df0cf4aaa944c1c5c2f490ae1d
    plan: free
    autoDeploy: true
