# render.yaml
services:
  - type: web
    name: artgallery
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn artgallery.wsgi --log-file -"
    envVars:
      - key: DJANGO_SECRET_KEY
        value: "a7dbea91a14fc3cebfac8963939b7a98"
    plan: free
    autoDeploy: true
