# render.yaml
services:
  - type: web
    name: art_gallery_test
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn artgallery.wsgi --log-file -"
    envVars:
      - key: DJANGO_SECRET_KEY
        value: your_secret_key_here
      - key: DATABASE_URL
        fromDatabase:
          name: artgallery-db
          property: connectionString
    plan: free
    autoDeploy: true

'''databases:
  - name: artgallery-db
    databaseName: artgallery
    user: artgallery_user
    password: artgallery_password
    plan: free'''
